### ISSUE TITLE
Verification role in config should be ID, not name

### ISSUE THREAD

**Issue by MiningMark48** [jensengillett/verificationbot#17]
Currently, in the config, setting the verification role is currently done by using the name. This should use the role's ID instead, to be more consistent with the other configs. This has created confusion... cc @jensengillett

**Comment by jensengillett** [comment]
I wasted an hour of my life and a few hours of other people's lives trying to figure out why this wasn't working on someone else's setup, and successfully made the same mistake on my own test deployment, which is indication enough that the design was flawed from the start...

**Comment by MiningMark48** [comment]
Benefit of doing it by [3e7e0d7](https://github.com/jensengillett/verificationbot/commit/482775b0e21762f879801e809031f22b2d708125): backwards compatibility
