### ISSUE TITLE
Improve aliases supported for !email

### ISSUE THREAD

**Issue by jensengillett** [jensengillett/verificationbot#20]
Common fails:

- !youremail@email.com  -  catch all commands, check if the entire command is a valid email and redirect
- ! email youremail@email.com  - alias ' email' to 'email'
- email youremail@email.com  - no easy way (no alias)
- youremail@email.com  - no easy way (no alias)
- !emailyouremail@email.com  - catch all commands, check if command contains 'email', then grab just the contents after and redirect

Should be easily able to handle 3/5 of these cases, which would hopefully improve ease of use for people that can't read messages properly and manage to fail multiple times because they try the same thing expecting a different result...

**Comment by jensengillett** [comment]
@MiningMark48 , could you see if there's an easy way for discord.py to have a default command handler?

**Comment by MiningMark48** [comment]
@jensengillett By "default command handler", I assume you mean something that can automagically handle common fails?

**Comment by jensengillett** [comment]
Basically, a fallback for a command not being found, but the alias being present at the beginning of the command. I'm not sure there's something that can do that in discord.py though.

**Comment by MiningMark48** [comment]
> !youremail@email.com - catch all commands, check if the entire command is a valid email and redirect
Doable.

> ! email youremail@email.com - alias ' email' to 'email'
*Should* be doable. Should be able to allow the command key to have a space after it. [Line](! email youremail@email.com - alias ' email' to 'email') of code in question.

> email youremail@email.com - no easy way (no alias)
Doable, but not clean and will decrease performance as every message would have to be read and checked if it is a command.

> youremail@email.com - no easy way (no alias)
Doable, but not clean and will decrease performance unless you used a dedicated channel.

> !emailyouremail@email.com - catch all commands, check if command contains 'email', then grab just the contents after and redirect
Doable, may decrease performance.

**Comment by MiningMark48** [comment]
> Basically, a fallback for a command not being found, but the alias being present at the beginning of the command. I'm not sure there's something that can do that in discord.py though.

I doubt it, but I'll check. Discord.py does have command "checks" which are basically annotations that can be added to the top of command methods so they can be used commonly on other commands. I just have to write a check that will do so.

**Comment by MiningMark48** [comment]
> > Basically, a fallback for a command not being found, but the alias being present at the beginning of the command. I'm not sure there's something that can do that in discord.py though.
> 
> I doubt it, but I'll check. Discord.py does have command "checks" which are basically annotations that can be added to the top of command methods so they can be used commonly on other commands. I just have to write a check that will do so.

Best that I can tell... no. No easy solution built into Discord.py directly, as expected.

**Comment by jensengillett** [comment]
I'm not too worried about overall performance decreases, the volume of messages is so low in the searched channel anyway that it's nbd as long as you make sure it's just that channel being looked at. 

> youremail@email.com - no easy way (no alias)
> Doable, but not clean and will decrease performance unless you used a dedicated channel.

I have some good news for you: the bot already limits verification to a specific channel. Specified by `channel_id` in the environment variables. 

The ones that aren't clean... if you can make it magically happen, that would be amazing, but I already know they're fairly unrealistic. They came from the list of 'common things people get wrong', but the lack of the alias at the front makes them _really_ problematic.

**Comment by jensengillett** [comment]
> Best that I can tell... no. No easy solution built into Discord.py directly, as expected.
That's really unfortunate, would have made it far easier.

**Comment by MiningMark48** [comment]
I'll see if I can work some magic.

**Comment by MiningMark48** [comment]
Two down so far.


Prefix with space after (Ex: `$ email`):
![](https://f000.backblazeb2.com/file/miningmark48-files/2021/06/17/DiscordPTB_2021-06-17_13-20-19.png)

Prefix with just email: (Ex: `!email@email.com`)
![](https://f000.backblazeb2.com/file/miningmark48-files/2021/06/17/DiscordPTB_2021-06-17_13-40-04.png)

**Comment by jensengillett** [comment]
Figured the first one would be easy, but didn't expect you'd manage the second one so quickly - excellent work! Looks like it wasn't too much work overall, thankfully. That `is_valid_email` function may be useful elsewhere too - you could potentially change the validation steps in the main email function to use it with a little tweaking. Great work so far!

**Comment by MiningMark48** [comment]
> That is_valid_email function may be useful elsewhere too - you could potentially change the validation steps in the main email function to use it with a little tweaking.

That was the plan. Was focusing on the issue first.

**Comment by MiningMark48** [comment]
> > That is_valid_email function may be useful elsewhere too - you could potentially change the validation steps in the main email function to use it with a little tweaking.
> 
> That was the plan. Was focusing on the issue first.

This is now done.

**Comment by MiningMark48** [comment]
If email is in specific channel:
![](https://f000.backblazeb2.com/file/miningmark48-files/2021/06/17/DiscordPTB_2021-06-17_14-35-35.png)

**Comment by MiningMark48** [comment]
No prefix, just command name:
![](https://f000.backblazeb2.com/file/miningmark48-files/2021/06/17/DiscordPTB_2021-06-17_15-20-32.png)

**Comment by MiningMark48** [comment]
No spaces:
![](https://f000.backblazeb2.com/file/miningmark48-files/2021/06/17/DiscordPTB_2021-06-17_15-25-04.png)

**Comment by MiningMark48** [comment]
> I'll see if I can work some magic.

I was able to work some magic.

**Comment by jensengillett** [comment]
Did not expect you to finish this so quickly (or at all for some of them, honestly). Do you need additional testing to verify that everything's good?

**Comment by MiningMark48** [comment]
Everything is good from my testing 👍

**Comment by jensengillett** [comment]
Merging to main then 👍
