### ISSUE TITLE
Readme file has a typo

### ISSUE THREAD

**Issue by swmorrow** [jensengillett/verificationbot#47]
In the readme file directing how to run the bot, there is a typo saying to run "python boy.py" when it should be "python bot.py". This can be fixed by renaming bot.py to boy.py, and changing the names of all other references to said file
![unknown](https://user-images.githubusercontent.com/94878706/173307120-588bdb11-60b6-4325-900f-d3d6d4bc09ba.png)
.

**Comment by jensengillett** [comment]
Thanks, @MiningMark48 
![image](https://user-images.githubusercontent.com/62229586/173972118-785aa559-c270-4b16-9e07-d6f4a7a35b9c.png)
